#!/bin/bash
# install.sh — idempotent setup for the portable Claude Code methodology.
#
# Sets up:
#   - Symlinks selected skills to ~/.claude/skills/
#   - Configures Claude Code settings fragment with the diary path
#   - Refuses to run if install dir or DIARY_PATH lies under a work-managed root
#
# Usage:
#   DIARY_PATH=~/iCloud-Drive/diary ./install.sh           # install
#   ./install.sh --uninstall                                # remove symlinks + settings
#
# Environment:
#   DIARY_PATH      Required for install. Where diary entries will be written.
#                   MUST be in personal-managed storage (iCloud, Dropbox, personal git).
#   WORK_PATHS      Optional. Comma-separated path prefixes treated as work-managed.
#                   Defaults to: /work,/Work,/opt/enterprise,/opt/company,~/Work,~/work
#   CLAUDE_HOME     Optional. Defaults to ~/.claude

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLAUDE_HOME="${CLAUDE_HOME:-$HOME/.claude}"
WORK_PATHS_DEFAULT="/work,/Work,/opt/enterprise,/opt/company,${HOME}/Work,${HOME}/work"
WORK_PATHS="${WORK_PATHS:-$WORK_PATHS_DEFAULT}"

err() { echo "ERROR: $*" >&2; exit 1; }
warn() { echo "WARN: $*" >&2; }
info() { echo "INFO: $*"; }

is_under_work_path() {
    local target="$1"
    local abs
    abs=$(cd "$(dirname "$target")" 2>/dev/null && pwd)/$(basename "$target")
    IFS=',' read -ra paths <<< "$WORK_PATHS"
    for p in "${paths[@]}"; do
        # Expand ~ if present
        p="${p/#\~/$HOME}"
        if [[ "$abs" == "$p"* ]]; then
            echo "$p"
            return 0
        fi
    done
    return 1
}

uninstall() {
    info "Uninstalling — removing symlinks and Claude Code settings fragment."
    local skills_dir="$CLAUDE_HOME/skills"
    if [ -d "$skills_dir" ]; then
        for sk in "$REPO_DIR"/claude-skills/*/; do
            name=$(basename "$sk")
            target="$skills_dir/$name"
            if [ -L "$target" ]; then
                rm "$target"
                info "  removed symlink: $target"
            fi
        done
    fi
    local frag="$CLAUDE_HOME/settings.local.claude-personal-fragment.json"
    if [ -f "$frag" ]; then
        rm "$frag"
        info "  removed settings fragment: $frag"
    fi
    info "Uninstall complete. Diary entries left untouched."
    exit 0
}

if [ "${1:-}" = "--uninstall" ]; then
    uninstall
fi

# Pre-flight: refuse to run from a work-managed path
matched=$(is_under_work_path "$REPO_DIR" || true)
if [ -n "$matched" ]; then
    err "Install dir '$REPO_DIR' is under work-managed path '$matched'.
Move this repo to a personal-only directory (e.g. ~/.config/claude-personal/)
before installing. The methodology is portable; the install location must be
personally-managed to keep the IP boundary clean."
fi

# Require DIARY_PATH
if [ -z "${DIARY_PATH:-}" ]; then
    err "DIARY_PATH is required.
Set it to a personal-managed storage location (iCloud, Dropbox, personal
git repo clone, etc.). Example:
  DIARY_PATH=~/iCloud-Drive/diary ./install.sh"
fi

# Resolve DIARY_PATH absolutely
DIARY_PATH="${DIARY_PATH/#\~/$HOME}"

matched=$(is_under_work_path "$DIARY_PATH" || true)
if [ -n "$matched" ]; then
    err "DIARY_PATH '$DIARY_PATH' is under work-managed path '$matched'.
Diary entries written from a work workstation MUST live in personal-managed
storage to keep the IP boundary clean. Pick a different path:
  - ~/iCloud-Drive/diary/
  - ~/Dropbox/diary/
  - ~/.diary/  (if backed up to a personal-only cloud)
  - A personal-account git repo cloned to a personal-only path."
fi

# Create DIARY_PATH if it doesn't exist
mkdir -p "$DIARY_PATH"
info "Diary path: $DIARY_PATH"

# Symlink skills
mkdir -p "$CLAUDE_HOME/skills"
for sk in "$REPO_DIR"/claude-skills/*/; do
    name=$(basename "$sk")
    target="$CLAUDE_HOME/skills/$name"
    if [ -L "$target" ]; then
        # Already symlinked; verify it points at our repo
        actual=$(readlink "$target")
        if [ "$actual" = "$sk" ] || [ "$actual" = "${sk%/}" ]; then
            info "  ✓ $name (symlink already in place)"
            continue
        fi
        warn "  ⚠ $target already points at $actual (not ours); skipping"
        continue
    fi
    if [ -e "$target" ]; then
        warn "  ⚠ $target exists (not a symlink); skipping. Move or remove it manually if you want this skill linked."
        continue
    fi
    ln -s "$sk" "$target"
    info "  ✓ symlinked $name"
done

# Write Claude Code settings fragment
frag="$CLAUDE_HOME/settings.local.claude-personal-fragment.json"
cat > "$frag" <<EOF
{
  "_comment": "Generated by claude-personal-config/install.sh — do not edit by hand. Re-run install.sh to update.",
  "diary": {
    "path": "$DIARY_PATH",
    "methodology_ref": "$REPO_DIR/diary/README.md"
  }
}
EOF
info "  ✓ wrote settings fragment: $frag"

cat <<EOF

Install complete.

  Skills linked under:  $CLAUDE_HOME/skills/
  Settings fragment:    $frag
  Diary entries land:   $DIARY_PATH

To verify: ask Claude Code to list available skills — the cluster-agnostic
set from this repo should appear.

To uninstall: ./install.sh --uninstall
EOF
